services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
    bind:
      $localDatabase: '@In2code.In2publishCore.Database.Local'
      $foreignDatabase: '@In2code.In2publishCore.Database.Foreign'
      $cache: '@cache.in2publish_core'
      array $extConf: '@=service("TYPO3\\CMS\\Core\\Configuration\\ExtensionConfiguration").get("in2publish_core")'

  In2code\In2publishCore\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  # Services

  In2code.In2publishCore.Database.Local:
    class: 'TYPO3\CMS\Core\Database\Connection'
    factory: ['@In2code\In2publishCore\Factory\ConnectionFactory', 'createLocalConnection']

  In2code.In2publishCore.Database.Foreign:
    class: 'TYPO3\CMS\Core\Database\Connection'
    factory: ['@In2code\In2publishCore\Factory\ConnectionFactory', 'createForeignConnection']

  In2code\In2publishCore\Domain\PostProcessing\Processor\PostProcessor:
    factory: ['@In2code\In2publishCore\Domain\PostProcessing\PostProcessorFactory', 'createPostProcessor']

  In2code\In2publishCore\Domain\Factory\FolderRecordFactory:
    public: true

  In2code\In2publishCore\Domain\Factory\IndexingFolderRecordFactory:
    public: true

  In2code\In2publishCore\Domain\Repository\CommonRepository:
    public: true

  In2code\In2publishCore\Service\Environment\ForeignEnvironmentService:
    public: true

  In2code\In2publishCore\Domain\PostProcessing\Processor\FalIndexPostProcessor:
    public: true

  In2code\In2publishCore\Domain\PostProcessing\Processor\FileIndexPostProcessor:
    public: true

  In2code\In2publishCore\Features\WarningOnForeign\Service\HeaderWarningColorRenderer:
    public: true

  In2code\In2publishCore\Service\Permission\PermissionService:
    public: true

  In2code\In2publishCore\Features\ContextMenuPublishEntry\Controller\PublishPageAjaxController:
    public: true

  In2code\In2publishCore\Features\RedirectsSupport\DataProvider\ForeignSiteIdentifierItemProcFunc:
    public: true

  cache.in2publish_core:
    class: TYPO3\CMS\Core\Cache\Frontend\FrontendInterface
    factory: ['@TYPO3\CMS\Core\Cache\CacheManager', 'getCache']
    arguments: ['in2publish_core']

  # Commands

  In2code\In2publishCore\Command\PublishTaskRunner\RunTasksInQueueCommand:
    tags:
      - name: 'console.command'
        command: 'in2publish_core:publishtasksrunner:runtasksinqueue'
        description: >
          Reads all Tasks to execute from the Database and executes them one after another.
          The success of a Task is echoed to the console or scheduler backend module, including any error message of failed tasks.
          NOTE: This command is used for internal operations in in2publish_core
        hidden: true

  In2code\In2publishCore\Command\RemoteProcedureCall\ExecuteCommand:
    tags:
      - name: 'console.command'
        command: 'in2publish_core:rpc:execute'
        description: 'Receives an envelope and executes the contained command'
        hidden: true

  In2code\In2publishCore\Command\Status\AllCommand:
    tags:
      - name: 'console.command'
        command: 'in2publish_core:status:all'
        description: 'Prints the configured fileCreateMask and folderCreateMask'
        hidden: true

  In2code\In2publishCore\Command\Status\AllSitesCommand:
    tags:
      - name: 'console.command'
        command: 'in2publish_core:status:allsites'
        description: 'Prints all Sites serialized and encoded. Internal CLI API.'
        hidden: true

  In2code\In2publishCore\Command\Status\ConfigFormatTestCommand:
    tags:
      - name: 'console.command'
        command: 'in2publish_core:status:configformattest'
        description: 'Tests the configuration on foreign for its format'
        hidden: true

  In2code\In2publishCore\Command\Status\CreateMasksCommand:
    tags:
      - name: 'console.command'
        command: 'in2publish_core:status:createmasks'
        description: 'Prints the configured fileCreateMask and folderCreateMask'
        hidden: true

  In2code\In2publishCore\Command\Status\DbConfigTestCommand:
    tags:
      - name: 'console.command'
        command: 'in2publish_core:status:dbconfigtest'
        description: 'Reads from the local task table and writes all found hashes for the db config test'
        hidden: true

  In2code\In2publishCore\Command\Status\DbInitQueryEncodedCommand:
    tags:
      - name: 'console.command'
        command: 'in2publish_core:status:dbinitqueryencoded'
        description: 'Prints the initCommands as json and base64 encoded string'
        hidden: true

  In2code\In2publishCore\Command\Status\GlobalConfigurationCommand:
    tags:
      - name: 'console.command'
        command: 'in2publish_core:status:globalconfiguration'
        description: 'Prints global configuration values'
        hidden: true

  In2code\In2publishCore\Command\Status\EncryptionKeyCommand:
    tags:
      - name: 'console.command'
        command: 'in2publish_core:status:encryptionkey'
        description: 'Prints the encryption key as base64 encoded string'
        hidden: true

  In2code\In2publishCore\Command\Status\ShortSiteConfigurationCommand:
    tags:
      - name: 'console.command'
        command: 'in2publish_core:status:shortsiteconfiguration'
        description: 'Prints a base64 encoded json array containing all configured sites'
        hidden: true

  In2code\In2publishCore\Command\Status\SiteConfigurationCommand:
    tags:
      - name: 'console.command'
        command: 'in2publish_core:status:siteconfiguration'
        description: 'Outputs the requested Site serialized and encoded.'
        hidden: true

  In2code\In2publishCore\Command\Status\Typo3VersionCommand:
    tags:
      - name: 'console.command'
        command: 'in2publish_core:status:typo3version'
        description: 'Prints TYPO3 version'
        hidden: true

  In2code\In2publishCore\Command\Status\VersionCommand:
    tags:
      - name: 'console.command'
        command: 'in2publish_core:status:version'
        description: 'Prints the version number of the currently installed in2publish_core extension'
        hidden: true

  In2code\In2publishCore\Command\Table\BackupCommand:
    tags:
      - name: 'console.command'
        command: 'in2publish_core:table:backup'
        description: 'Stores a backup of the complete local table into the configured directory'

  In2code\In2publishCore\Command\Table\ImportCommand:
    tags:
      - name: 'console.command'
        command: 'in2publish_core:table:import'
        description: 'Stores a backup of the complete local table into the configured directory'

  In2code\In2publishCore\Command\Table\PublishCommand:
    tags:
      - name: 'console.command'
        command: 'in2publish_core:table:publish'
        description: 'Copies a complete table from stage to production and overwrites all old entries!'

  In2code\In2publishCore\Command\Tools\TestCommand:
    tags:
      - name: 'console.command'
        command: 'in2publish_core:tools:test'
        description: >
          Executes the in2publish_core backend tests.
          Enable verbose mode if you want to see a success message.
          For scripted testing check the exit code of this command.

  # EventListener

  In2code\In2publishCore\Domain\PostProcessing\PostProcessingEventListener:
    tags:
      - name: event.listener
        identifier: 'in2publishcore-postprocessingeventlistener-recordinstancewasinstantiated'
        method: 'onRecordInstanceWasInstantiated'
        event: In2code\In2publishCore\Event\RecordInstanceWasInstantiated
      - name: event.listener
        identifier: 'in2publishcore-postprocessingeventlistener-rootrecordcreationwasfinished'
        method: 'onRootRecordCreationWasFinished'
        event: In2code\In2publishCore\Event\RootRecordCreationWasFinished

  In2code\In2publishCore\Features\CacheInvalidation\Domain\Anomaly\CacheInvalidator:
    tags:
      - name: event.listener
        identifier: 'in2publishcore-CacheInvalidator-PublishingOfOneRecordBegan'
        method: 'registerClearCacheTasks'
        event: In2code\In2publishCore\Event\PublishingOfOneRecordBegan
      - name: event.listener
        identifier: 'in2publishcore-CacheInvalidator-RecursiveRecordPublishingEnded'
        method: 'writeClearCacheTask'
        event: In2code\In2publishCore\Event\RecursiveRecordPublishingEnded

  In2code\In2publishCore\Features\PhysicalFilePublisher\Domain\Anomaly\PhysicalFilePublisher:
    tags:
      - name: event.listener
        identifier: 'in2publishcore-PhysicalFilePublisher-PublishingOfOneRecordEnded'
        method: 'publishPhysicalFileOfSysFile'
        event: In2code\In2publishCore\Event\PublishingOfOneRecordEnded

  In2code\In2publishCore\Features\SysLogPublisher\Domain\Anomaly\SysLogPublisher:
    tags:
      - name: event.listener
        identifier: 'in2publishcore-SysLogPublisher-PublishingOfOneRecordEnded'
        method: 'publishSysLog'
        event: In2code\In2publishCore\Event\PublishingOfOneRecordEnded

  In2code\In2publishCore\Features\RefIndexUpdate\Domain\Anomaly\RefIndexUpdater:
    tags:
      - name: event.listener
        identifier: 'in2publishcore-RefIndexUpdater-PublishingOfOneRecordEnded'
        method: 'registerRefIndexUpdate'
        event: In2code\In2publishCore\Event\PublishingOfOneRecordEnded
      - name: event.listener
        identifier: 'in2publishcore-RefIndexUpdater-RecursiveRecordPublishingEnded'
        method: 'writeRefIndexUpdateTask'
        event: In2code\In2publishCore\Event\RecursiveRecordPublishingEnded

  In2code\In2publishCore\Features\FileEdgeCacheInvalidator\Domain\Anomaly\PublishedFileIdentifierCollector:
    tags:
      - name: event.listener
        identifier: 'in2publishcore-PublishedFileIdentifierCollector-PhysicalFileWasPublished'
        method: 'registerPublishedFile'
        event: In2code\In2publishCore\Event\PhysicalFileWasPublished
      - name: event.listener
        identifier: 'in2publishcore-PublishedFileIdentifierCollector-RecursiveRecordPublishingEnded'
        method: 'writeFlushFileEdgeCacheTask'
        event: In2code\In2publishCore\Event\RecursiveRecordPublishingEnded

  In2code\In2publishCore\Features\PublishSorting\Domain\Anomaly\SortingPublisher:
    tags:
      - name: event.listener
        identifier: 'in2publishcore-SortingPublisher-PublishingOfOneRecordBegan'
        method: 'collectSortingsToBePublished'
        event: In2code\In2publishCore\Event\PublishingOfOneRecordBegan
      - name: event.listener
        identifier: 'in2publishcore-SortingPublisher-RecursiveRecordPublishingEnded'
        method: 'publishSortingRecursively'
        event: In2code\In2publishCore\Event\RecursiveRecordPublishingEnded

  In2code\In2publishCore\Features\SkipEmptyTable\SkipTableVoter:
    tags:
      - name: event.listener
        identifier: 'in2publishcore-SkipTableVoter-VoteIfSearchingForRelatedRecordsByPropertyShouldBeSkipped'
        method: 'shouldSkipSearchingForRelatedRecordsByProperty'
        event: In2code\In2publishCore\Event\VoteIfSearchingForRelatedRecordsByPropertyShouldBeSkipped
      - name: event.listener
        identifier: 'in2publishcore-SkipTableVoter-VoteIfFindingByIdentifierShouldBeSkipped'
        method: 'shouldSkipFindByIdentifier'
        event: In2code\In2publishCore\Event\VoteIfFindingByIdentifierShouldBeSkipped
      - name: event.listener
        identifier: 'in2publishcore-SkipTableVoter-VoteIfFindingByPropertyShouldBeSkipped'
        method: 'shouldSkipFindByProperty'
        event: In2code\In2publishCore\Event\VoteIfFindingByPropertyShouldBeSkipped
      - name: event.listener
        identifier: 'in2publishcore-SkipTableVoter-VoteIfSearchingForRelatedRecordsByTableShouldBeSkipped'
        method: 'shouldSkipSearchingForRelatedRecordByTable'
        event: In2code\In2publishCore\Event\VoteIfSearchingForRelatedRecordsByTableShouldBeSkipped

  In2code\In2publishCore\Config\Provider\PageTsProvider:
    tags:
      - name: event.listener
        identifier: 'in2publishcore-PageTsProvider-bootCompleted'
        method: 'processData'
        event: TYPO3\CMS\Core\Core\Event\BootCompletedEvent
